### ISSUE TITLE
Security Headers

### ISSUE THREAD

**Issue by DSMaVie** [QuITAC/proxy_docker#1]
A bunch of features require proper login checks and so on. Secure Headers are the first step for that.

**Comment by DSMaVie** [comment]
Linked to https://github.com/QuITAC/authentik/issues/3

**Comment by DSMaVie** [comment]
Remember HSTS Header

**Comment by NattCaat** [comment]
- CSP: Ist da, wir werden das testen und dann Enforcing setzen
- HSTS: Muss noch gemacht werden
